### ISSUE TITLE
/etc/iotedge/config.yaml - moby_runtime section doesn't work

### ISSUE THREAD

**Issue by gri6507** [Azure/iotedge#2183]
I am following the documentation from https://github.com/Azure/iotedge/blob/master/doc/networking.md to try to create a custom bridged network on which my edge module should run.

I modified `/etc/iotedge/config.yaml` such that
```yaml
moby_runtime:
  uri: "unix:///var/run/docker.sock"
  network: "azure-iot-edge"
  ipv6: false
  ipam:
    config:
      gateway: "172.19.0.1"
      subnet: "172.19.0.0/16"
      ip_range: "172.19.0.0/16"
```

I then restarted `iotedge` service with `sudo systemctl restart iotedge`. However, when I run `ip addr` on my ubuntu 18.04 host machine, I see
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:32:8c:ce brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic eth0
       valid_lft 85388sec preferred_lft 85388sec
    inet6 fe80::a00:27ff:fe32:8cce/64 scope link 
       valid_lft forever preferred_lft forever
3: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:00:38:da:23 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:ff:fe38:da23/64 scope link 
       valid_lft forever preferred_lft forever
4: br-8cc2c3237299: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:86:8a:91:bc brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 brd 172.18.255.255 scope global br-8cc2c3237299
       valid_lft forever preferred_lft forever
    inet6 fe80::42:86ff:fe8a:91bc/64 scope link 
       valid_lft forever preferred_lft forever
14: vetha6858b6@if13: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether 42:e0:1b:7a:df:fe brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::40e0:1bff:fe7a:dffe/64 scope link 
       valid_lft forever preferred_lft forever
16: vethdb18a6c@if15: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-8cc2c3237299 state UP group default 
    link/ether 9a:70:16:b0:f3:b4 brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::9870:16ff:feb0:f3b4/64 scope link 
       valid_lft forever preferred_lft forever
18: veth23bd386@if17: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-8cc2c3237299 state UP group default 
    link/ether 46:9f:be:8c:4c:3f brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::449f:beff:fe8c:4c3f/64 scope link 
       valid_lft forever preferred_lft forever
```
and by running `docker container ls` to get the containerId within which the edge module is running, and then running `docker exec -it <containerid> cat /etc/hosts` I see that the module is running on the `br-8cc2c3237299` network. Why is this docker bridge network not called `azure-iot-edge` as documentation implies? What is the correct way to name the network and make the edge module run on that network?

**Comment by vipeller** [comment]
Hi,

I think you made a mistake with hierarchy:
the "network" setting has multiple sub-settings as "name", "ipv6", "ipam"
in your case, "network" is defined as a string and "ipv6", "ipam" is a part of "moby_runtime" - which is a wrong level, also you don't have "name" property defined. Let me know if re-arranging the config file solves the problem.

![netconfig](https://user-images.githubusercontent.com/51135538/71494517-9bf52e80-27fc-11ea-81d5-ce129e74c09e.png)

**Comment by gri6507** [comment]
@vipeller Thank you. I believe you are correct. Here is my working config.yaml section

```yaml
moby_runtime:
  uri: "unix:///var/run/docker.sock"
  network: "my-foo2"
  ipv6: false
  ipam:
    config:
      gateway: '172.21.0.1'
      subnet: '172.21.0.0/16'
      ip_range: '172.21.0.0/16'
```

There are however, several caveats:
 1. if the edgeHub or any custom module were already running as docker containers, those docker containers have to be deleted first so that iotedge daemon will re-launch them on the correct network.
 1. if the network **name** is not being changed, then you have to first `docker network prune` to delete the old instance of the network.

Lastly, this means that the documentation on https://github.com/Azure/iotedge/blob/master/doc/networking.md is not correctly indented. Since YAML is a whitespace indented language, this seems like a crucial mistake which should be corrected!

**Comment by vipeller** [comment]
@gri6507 one little thing, "config" section is a list of settings, so you need to put a dash (-). You could add multiple gateway/subnet/ip_range to the config section, all are individual items in the list, and you need to separate them using a dash. I know that it is confusing when you have only a single item. (opening https://github.com/Azure/iotedge/blob/master/doc/networking.md you will see where the dash should go) Let me know if it fixed the problem

**Comment by gri6507** [comment]
Ok, here's my config section with the dash
```yaml
moby_runtime:
  uri: "unix:///var/run/docker.sock"
  network:
          name: "my-foo3"
          ipv6: false
          ipam:
            config:
              -
                gateway: "172.42.0.1"
                subnet: "172.42.0.0/16"
                ip_range: "172.42.0.0/16"
```
This also fails. Here's the journalctl log
```
Jan 06 12:55:33 abyss systemd[1]: Started Azure IoT Edge daemon.
Jan 06 12:55:33 abyss iotedged[2663]: 2020-01-06T18:55:33Z [INFO] - Using config file: /etc/iotedge/config.yaml
Jan 06 12:55:33 abyss iotedged[2663]: 2020-01-06T18:55:33Z [ERR!] - The daemon could not start up successfully: Could not load settings
Jan 06 12:55:33 abyss iotedged[2663]: 2020-01-06T18:55:33Z [ERR!] -         caused by: Could not load settings
Jan 06 12:55:33 abyss iotedged[2663]: 2020-01-06T18:55:33Z [ERR!] -         caused by: invalid type: map, expected a string
Jan 06 12:55:33 abyss systemd[1]: iotedge.service: Main process exited, code=exited, status=1/FAILURE
Jan 06 12:55:33 abyss systemd[1]: iotedge.service: Failed with result 'exit-code'.

```

**Comment by vipeller** [comment]
@gri6507 I think that is because there is no space after the dash but a new line immediately. In yaml a space is needed after dash to signal the start of the new item in a list.

**Comment by gri6507** [comment]
@vipeller - wow, the space after the dash was my problem. Thank you!

1. Can the https://github.com/Azure/iotedge/blob/master/doc/networking.md page add a special note clarifying the need for the dashes and a space after them
1. Where can I find a complete specification for YAML syntax?

**Comment by vipeller** [comment]
@gri6507 this is the specification:  https://yaml.org/spec/

we are going to update the "networking" page, I understand that this is confusing.

**Comment by arsing** [comment]
The `networking.md` example is formatted strangely. I would've written it like this:

```yaml
    ipam:
      config:
      - gateway: '172.18.0.1'
        subnet: '172.18.0.0/16'
        ip_range: '172.18.0.0/16'
      - gateway: '2021:ffff:e0:3b1:1::1'
        subnet: '2021:ffff:e0:3b1:1::/80'
        ip_range: '2021:ffff:e0:3b1:1::/80'
```

which is much easier to read, and you don't have to worry about a trailing whitespace after the `-`.
