### ISSUE TITLE
Cannot Initialize IoTEdge on Windows with Linux containers

### ISSUE THREAD

**Issue by r3dlin3** [Azure/iotedge#2447]
## Expected Behavior

After deploying the IotEdge runtime, we should be able to initialize it

## Current Behavior
Error raised during initialization

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Deploy IoT Edge
```
> Deploy-IoTEdge -ContainerOs Linux
Docker is running.
AVERTISSEMENT : Linux containers on Windows can be used for development and testing, but are not supported in
production IoT Edge deployments. See https://aka.ms/iotedge-platsup for more details.
The container host is on supported build version 18363.
Skipping VC Runtime installation because it is already installed.
Downloading IoT Edge...
Using IoT Edge from C:\Users\XXX\AppData\Local\Temp\microsoft-azure-iotedge.cab
To complete the installation, run "Initialize-IoTEdge".
```
2. Try to initialize
```
PS C:\WINDOWS\system32> Initialize-IoTEdge -ContainerOs Linux

applet de commande Initialize-IoTEdge à la position 1 du pipeline de la commande
Fournissez des valeurs pour les paramètres suivants :
DeviceConnectionString: HostName=XXX.azure-devices.net;DeviceId=myEdgeDevice;SharedAccessKey=XXX
Docker is running.
AVERTISSEMENT : Linux containers on Windows can be used for development and testing, but are not supported in
production IoT Edge deployments. See https://aka.ms/iotedge-platsup for more details.
The container host is on supported build version 18363.
Generating config.yaml...
Configured device for manual provisioning.
Configured device with hostname 'DESKTOP-L3JJNVA'.
Initialize-IoTEdge : La propriété « IPAddress » est introuvable dans cet objet. Vérifiez qu’elle existe.
Au caractère Ligne:1 : 1
+ Initialize-IoTEdge -ContainerOs Linux
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Initialize-IoTEdge], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict,Initialize-IoTEdge
```
Note:
```
S C:\WINDOWS\system32> $Error
Au caractère Ligne:1676 : 5
+     $gatewayAddress = (Get-NetIpAddress |
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict]
```
3.
4.

### Output of `iotedge check`
N/A
iotedge is missing

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: Windows 10 18363
* Architecture [e.g. amd64, arm32, arm64]: amd64
* Container OS [e.g. Linux containers, Windows containers]:  Linux containers

### Runtime Versions
* iotedged [run `iotedge version`]: 
* Edge Agent [image tag (e.g. 1.0.0)]: 
* Edge Hub [image tag (e.g. 1.0.0)]: 
* Docker/Moby [run `docker version`]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

lient: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
## Additional Information
I have uninstall Edge, Docker to reinstall it wihout success.
I'm runnin Docker Desktop 2.2.0.0
List of interfaces:
```
Get-NetIpAddress |   Where-Object { $_.AddressFamily -eq 'IPv4'} | select InterfaceAlias
InterfaceAlias
--------------
vEthernet (Default Switch)
Connexion au réseau local* 4
Connexion au réseau local* 3
Connexion réseau Bluetooth
Ethernet
Cellulaire
Wi-Fi
Loopback Pseudo-Interface 1
```

**Comment by veyalla** [comment]
This seems related to https://github.com/docker/for-win/issues/5538
 
You might be able to be use Docker Desktop 2.1 as a workaround.

**Comment by r3dlin3** [comment]
Thanks @veyalla. As a temporary solution, I'm using a Linux VM.
However, the disappearance of DockerNAT seems a breaking change with no revert to the previous situation from what I'm reading.

**Comment by veyalla** [comment]
Yes, we might to figure out a different scheme in our install script, I was able to get it to work with the following config (setting env vars and/or firewall rules might need to be configured manually though, for now):

```
provisioning:
  source: 'manual'
  device_connection_string: 'replace-with-connection-string'
agent:
  name: "edgeAgent"
  type: "docker"
  env: {}
  config:
    image: "mcr.microsoft.com/azureiotedge-agent:1.0.8"
    auth: {}
hostname: 'replace-with-hostname'
connect:
  management_uri: "http://host.docker.internal:15580"
  workload_uri: "http://host.docker.internal:15581"
listen:
  management_uri: "http://0.0.0.0:15580"
  workload_uri: "http://0.0.0.0:15581"
homedir: "C:\\ProgramData\\iotedge"
moby_runtime:
  uri: "npipe://./pipe//docker_engine"
```
