### ISSUE TITLE
IoT Edge - using x.509 Certs without DPS

### ISSUE THREAD

**Issue by gerhard67** [Azure/iotedge#3363]
Hi, 

I try to add an IoT Edge Devices with x.509 certificates to IoT Hub. I generate all certificates as described here https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md and I registered the thumbprints on the Hub. 

When I ask for the device connection string via cloud shell by 

`az iot hub device-identity show-connection-string --device-id “<DEVICE-ID>" --hub-name “<HUBNAME>”` 

I get
```
{
"connectionString": "HostName=<IOTHUBURL>;DeviceId=<DEVICEID>;x509=true",
} 
```
what looks right. 

My config.yaml looks like 

```
provisioning:
  source: "manual"
  device_connection_string: “HostName=<IOTHUBURL>;DeviceId=<DEVICEID>;x509=true"

certificates:
   device_ca_cert: "<path to certs>/certs/iot-edge-device-=<DEVICEID>-primary-full-chain.cert.pem"
   device_ca_pk: "<path to certs>/private/iot-device-=<DEVICEID>-primary.key.pem" 
   trusted_ca_certs: "<path to certs>/certs/azure-iot-test-only.root.ca.cert.pem"
```

But my `iotedge check –verbose` delivers 
_× config.yaml has well-formed connection string – Error
    Invalid connection string format detected.
    Please check the value of the provisioning.device_connection_string parameter.
        caused by: The Connection String is **missing required parameter SharedAccessKey**_

Any idea why? Is for IoT Edge x.509 only supported via DPS? At least, I can't find this in the documentation.

**Comment by massand** [comment]
The `az iot hub device-identity` provides a generic connection string when the device uses X.509, which isn't useful for any tool without setting the path to the identity certificate and key (required for TLS authentication to IoT Hub). For IoT Edge, the IoT Hub manual X.509 provisioning mode configuration does not require a connection string. It requires breaking apart the connection string into separate YAML fields in the `/etc/iotedge/config.yaml`file (sidenote: take note of the precise indentation using 2 spaces at different hierarchical levels in your config.yaml)- 
```yaml
# Manual provisioning configuration using an X.509 identity certificate
provisioning:
  source: "manual"
  authentication:
    method: "x509"
    iothub_hostname: "<REQUIRED IOTHUB HOSTNAME>"
    device_id: "<REQUIRED DEVICE ID PROVISIONED IN IOTHUB>"
    identity_cert: "<REQUIRED URI TO DEVICE IDENTITY CERTIFICATE>"
    identity_pk: "<REQUIRED URI TO DEVICE IDENTITY PRIVATE KEY>"
  dynamic_reprovisioning: false
```

If using DPS X.509 provisioning mode, the `/etc/iotedge/config.yaml`file contains similar `identity_cert` and `identity_pk` YAML fields under the `# DPS X.509 provisioning configuration` section that can be uncommented and filled in.
