### ISSUE TITLE
How to set 'Attachable=true' on the azure-iot-edge network.

### ISSUE THREAD

**Issue by newmys** [Azure/iotedge#3973]
## Expected Behavior
I want to set `Attachable=ture` on the azure-iot-edge network

## Current Behavior
`Attachable=false` allways 

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. change the config file (`/etc/iotedge/config.yaml`) as below
```
...
moby_runtime:
  uri: "unix:///var/run/docker.sock"
  network:
    name: "azure-iot-edge"
    attachable: true
    ipam:
      config:
        - gateway: '172.18.0.1'
          subnet: '172.18.0.0/16'
          ip_range: '172.18.0.0/16'
```
2. restart iotedge service

### Output of `docker network inspect azure-iot-edge`

<details>
<summary>Click here</summary>

```

[
    {
        "Name": "azure-iot-edge",
        "Id": "xxxxxxxxxxxxxxxxxx",
        "Created": "2020-11-12T21:16:33.638959774-05:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "IPRange": "172.18.0.0/16",
                    "Gateway": "172.18.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "xxxxxxxxxxxxxxxxxx": {
                "Name": "edgeAgent",
                "EndpointID": "xxxxxxxxxxxxxxxxxx",
                "MacAddress": "xxxxxxxxxxxxxxxxxx",
                "IPv4Address": "172.18.0.1/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: CentOs7
* Architecture [e.g. amd64, arm32, arm64]: amd64
* Container OS [e.g. Linux containers, Windows containers]: Linux containers

### Runtime Versions
* iotedged [run `iotedge version`]: 1.0.9.5
* Edge Agent [image tag (e.g. 1.0.0)]: 1.0.0
* Edge Hub [image tag (e.g. 1.0.0)]: 1.0.0
* Docker/Moby [run `docker version`]:  docker 19.03.5
