### ISSUE TITLE
Edge Agent fails to start Edge Hub if we specify the network name as "host" in config.yaml

### ISSUE THREAD

**Issue by avranju** [Azure/iotedge#408]
Edge Agent fails to start Edge Hub if we specify the network name as `host` in `config.yaml`. For example:
```yaml
moby_runtime:
  uri: "unix:///var/run/docker.sock"
  network: "host"
```
The error seems to be that Edge Agent tries to add an alias name for the Edge Hub container and this is not supported by Docker for containers that are being started on the host network. The fix might be to not attempt creating an alias name for the Edge Hub container when we detect that it is being added to the host network.
