### ISSUE TITLE
Nested Edge deployment fails: "Error creating a device-to-cloud connection"

### ISSUE THREAD

**Issue by ksaye** [Azure/iotedge#5222]
## Expected Behavior
Following the instructions at https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-nested-iot-edge?view=iotedge-2020-11, I expect to see the lower-level run edgeHub and simulatedTemperatureSensor

## Current Behavior
I get the error:
```
<4> 2021-07-08 17:37:42.993 +00:00 [WRN] - Error creating a device-to-cloud connection
System.AggregateException: One or more errors occurred. (Transient network error occurred, please retry.) (Transient network error occurred, please retry.)
 ---> Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry.
 ---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name does not resolve
```

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Follow https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-nested-iot-edge?view=iotedge-2020-11

### Output of `iotedge check`
Support bundle for top-layer
[support_bundle_top.zip](https://github.com/Azure/iotedge/files/6786315/support_bundle_top.zip)

Support bundle for lower-layer
[support_bundle.zip](https://github.com/Azure/iotedge/files/6786318/support_bundle.zip)

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]:  Ubuntu 20.04
* Architecture [e.g. amd64, arm32, arm64]:  amd64
* Container OS [e.g. Linux containers, Windows containers]:  Linux

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.2.3
* Edge Agent [image tag (e.g. 1.0.0)]:  1.2
* Edge Hub [image tag (e.g. 1.0.0)]:  1.2
* Docker/Moby [run `docker version`]: 20.10.7+azure

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by ksaye** [comment]
Update, I was able to get it to work.  The change was that I had to use FQDN the entire time.  Instead of using top-layer, I had to use top-layer.internal.cloudapp.net.  In Step 3, I had to put the FQDN: https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-nested-iot-edge?view=iotedge-2020-11#create-a-hierarchy-of-iot-edge-devices

```
config_version: "1.0"

iothub:
  iothub_hostname: bhtest.azure-devices.net
  iothub_name: bhtest
  ## Authentication method used by IoT Edge devices: symmetric_key or x509_certificate
  authentication_method: symmetric_key 

## Root certificate used to generate device CA certificates. Optional. If not provided a self-signed CA will be generated
# certificates:
#   root_ca_cert_path: ""
#   root_ca_cert_key_path: ""

## IoT Edge configuration template to use
configuration:
  template_config_path: "./templates/tutorial/device_config.toml"
  default_edge_agent: "$upstream:8000/azureiotedge-agent:1.2"

## Hierarchy of IoT Edge devices to create
edgedevices:
  device_id: top-layer.internal.cloudapp.net
  edge_agent: "mcr.microsoft.com/azureiotedge-agent:1.2" ## Optional. If not provided, default_edge_agent will be used
  deployment: "./templates/tutorial/deploymentTopLayer.json" ## Optional. If provided, the given deployment file will be applied to the newly created device
  # hostname: "FQDN or IP" ## Optional. If provided, install.sh will not prompt user for this value nor the parent_hostname value
  child:
    - device_id: lower-layer.internal.cloudapp.net
      deployment: "./templates/tutorial/deploymentLowerLayer.json" ## Optional. If provided, the given deployment file will be applied to the newly created device
      # hostname: "FQDN or IP" ## Optional. If provided, install.sh will not prompt user for this value nor the parent_hostname value
```

Which created the FQDN entries in IoT Hub:
![image](https://user-images.githubusercontent.com/15837044/124997003-88d93680-e00f-11eb-9028-f51f99c31983.png)

and I had to use the FQDN when running ./install.sh ( on the top-level):
![image](https://user-images.githubusercontent.com/15837044/124997135-c047e300-e00f-11eb-9808-8670dec37088.png)

and on the lower-level
![image](https://user-images.githubusercontent.com/15837044/124997275-ed949100-e00f-11eb-8944-e80f15a0be40.png)

which now we can see edgeAgent on the lower level connecting:
![image](https://user-images.githubusercontent.com/15837044/124997359-1452c780-e010-11eb-94d8-d7c7fa452af1.png)

As I think through it, perhaps if I had a search suffix assigned to the Docker network 'azure-iot-edge', it might have worked.

The way I resolve it was by running:
```
docker run -i -t --network azure-iot-edge ubuntu bash
```
and installing ping.  I noticed that could not ping top-layer.
