### ISSUE TITLE
Configuring Certificates on Device Results in Docker Error 

### ISSUE THREAD

**Issue by scout208** [Azure/iotedge#6722]
**Describe the Problem**
I'm trying to setup my IoT Edge device to act as a transparent gateway using EFLOW. I've followed along with the documentation [here](https://learn.microsoft.com/en-us/azure/iot-edge/how-to-create-transparent-gateway?view=iotedge-2018-06&tabs=eflow), but after configuring the certificates I start getting the following result when running `sudo iot edge check`.

````
Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
× config.yaml has correct URIs for daemon mgmt endpoint - Error
    SocketError - SocketErrorCode (ConnectionRefused) : Connection refused /var/lib/iotedge/mgmt.sock
    One or more errors occurred. (Got bad response: )
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: certificates - Warning
    The device CA cert will expire within the next 90 days, at 2022-11-06 20:23:08 UTC. Renew the certificate before this date to retain functionality.
    See https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: logs policy - OK
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

17 check(s) succeeded.
3 check(s) raised warnings. Re-run with --verbose for more details.
2 check(s) raised errors. Re-run with --verbose for more details.
````

**To Reproduce**
1. Follow the steps in the guide linked above from the beginning through the 'Configure certificates on device' section
2. Run `sudo iotedge check`
3. Observe results

**Expected behavior**
`sudo iotedge check` should return with no errors.

**Screenshots**

![image](https://user-images.githubusercontent.com/9426329/194914713-9a16c334-2c4b-4158-8404-8a739cd0df0a.png)

**Windows Host OS (please complete the following information):**
 - Edition: Windows IoT Enterprise LTSC 2021
 - Version: Build 21H2
 - Virtual Machine: None
 
**Additional context**

Here's the certificate section of my `config.yaml`:

````
###############################################################################
# Certificate settings
###############################################################################
#
# Configures the certificates required to operate the IoT Edge runtime
# as a gateway, which enables external leaf devices to securely
# communicate with the Edge Hub.
#
# If these values are not specified, the certificates
# will be auto generated by the daemon. This is useful for quickstart scenarios
# but is not intended for production environments.
#
# Settings:
#     device_ca_cert   - Path of the file containing the device CA certificate and its chain.
#                        The value must be specified as a "file" URI.
#                        Eg "file:///var/secrets/device-ca.pem"
#     device_ca_pk     - Path of the file containing the private key of the device CA certificate.
#                        The value must be specified as a "file" URI.
#                        Eg "file:///var/secrets/device-ca.key.pem"
#     trusted_ca_certs - Path of the file containing the containing
#                        all the trusted CA certificates required for Edge module communication.
#                        Edge modules and leaf devices use the certificates in this file to trust
#                        the server certificate of the Edge Hub, so this file must contain
#                        at least the device CA certificate specified in `device_ca_cert` above.
#                        The value must be specified as a "file" URI.
#                        Eg "file:///var/secrets/trusted-cas.pem"
#     auto_generated_ca_lifetime_days -
#                        The lifetime of the auto-generated workload CA certificate.
#                        If device_ca_cert and device_ca_pk have not been set (quickstart mode),
#                        then this is also used for the lifetime of
#                        the auto-generated device CA certificate.
#                        Defaults to 90 days.
#
###############################################################################

certificates:
  device_ca_cert: "file:///home/iotedge-user/certs/certs/iot-edge-device-RealEdgeDevCACert-full-chain.cert.pem"
  device_ca_pk: "file:///home/iotedge-user/certs/private/iot-edge-device-RealEdgeDevCACert.key.pem"
  trusted_ca_certs: "file:///home/iotedge-user/certs/certs/azure-iot-test-only.root.ca.cert.pem"
  auto_generated_ca_lifetime_days: 90
````
