### ISSUE TITLE
x509 identity certificate enrollment via EST for DPS with bootstrap certs does not work

### ISSUE THREAD

**Issue by djryanj** [Azure/iotedge#6960]
## Expected Behavior
Certificates should be issued properly.

## Current Behavior
When configured to use a bootstrap x509 certificate and key placed on the device to enroll for a device certificate via DPS, certificates are not provisioned. However, using the same config (except configured to use passcode), certificate is issued correctly. Of note, this is on Digicert's Digicert One platform and may be related to that platform (I have requested help from them as well).

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Using a `config.toml` such as:
    ```toml
    trust_bundle_cert = "file:///var/aziot/certs/digicert-root.cer"
    
    [provisioning]
    source = "dps"
    global_endpoint = "https://global.azure-devices-provisioning.net"
    id_scope = "<thescope>"
    
    [provisioning.attestation]
    method = "x509"
    registration_id = "<name>"
    
    [provisioning.attestation.identity_cert]
    method = "est"
    common_name = "<name>"
    
    [provisioning.attestation.identity_cert.auto_renew]
    rotate_key = false
    threshold = "80%"
    retry = "4%"

    [cert_issuance.est]
        trusted_certs = [
            "file:///var/aziot/certs/digicert-root.cer", # note that this has also been installed on the system for good measure
        ]
       
    [cert_issuance.est.auth]
    bootstrap_identity_cert = "file:///var/aziot/certs/digicert-auth.cer"
    bootstrap_identity_pk = "file:///var/aziot/secrets/digicert-privkey.key" 
    
    [cert_issuance.est.urls]
    
    default = "https://clientauth.one.digicert.com/.well-known/est/IOT_<endpoint>"
    ```

    Errors from `certd` and `identityd` are:
    ```bash
    Mar 15 16:54:43 <name> aziot-keyd[2313886]: 2023-03-15T22:54:43Z [INFO] - <-- POST /sign?api-version=2021-05-01 {"content-length": "335", "content-type": "application/json"}
    Mar 15 16:54:43 <name> aziot-keyd[2313886]: 2023-03-15T22:54:43Z [INFO] - --> 200 {"content-type": "application/json"}
    Mar 15 16:54:43 <name> aziot-certd[2313871]: 2023-03-15T22:54:43Z [ERR!] - !!! internal error
    Mar 15 16:54:43 <name> aziot-certd[2313871]: 2023-03-15T22:54:43Z [ERR!] - !!! caused by: could not create cert
    Mar 15 16:54:43 <name> aziot-certd[2313871]: 2023-03-15T22:54:43Z [ERR!] - !!! caused by: EST endpoint did not return successful response: 400 Bad Request b"<html>\r\n<head><title>400 The SSL certificate error</title></head>\r\n<body>\r\n<center><h1>400 Bad Request</h1></center>\r\n<center>The SSL certificate error</center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
    Mar 15 16:54:43 <name> aziot-certd[2313871]: 2023-03-15T22:54:43Z [INFO] - --> 500 {"content-type": "application/json"}
    Mar 15 16:54:43 <name> aziot-identityd[2497477]: 2023-03-15T22:54:43Z [ERR!] - service encountered an error
    Mar 15 16:54:43 <name> aziot-identityd[2497477]: 2023-03-15T22:54:43Z [ERR!] - caused by: internal error
    Mar 15 16:54:43 <name> aziot-identityd[2497477]: 2023-03-15T22:54:43Z [ERR!] - caused by: could not create certificate
    Mar 15 16:54:43 <name> aziot-identityd[2497477]: 2023-03-15T22:54:43Z [ERR!] - caused by: internal error
    Mar 15 16:54:43 <name> aziot-identityd[2497477]: 2023-03-15T22:54:43Z [ERR!] -    0: <unknown>
    Mar 15 16:54:43 <name> aziot-identityd[2497477]:    1: <unknown>
    Mar 15 16:54:43 <name> systemd[1]: aziot-identityd.service: Main process exited, code=exited, status=1/FAILURE
    Mar 15 16:54:43 <name> systemd[1]: aziot-identityd.service: Failed with result 'exit-code'.
    ```
3. However, using the following `config.toml` succeeds:
    ```toml
    trust_bundle_cert = "file:///var/aziot/certs/digicert-root.cer"
    
    [provisioning]
    source = "dps"
    global_endpoint = "https://global.azure-devices-provisioning.net"
    id_scope = "<thescope>"
    
    [provisioning.attestation]
    method = "x509"
    registration_id = "<name>"
    
    [provisioning.attestation.identity_cert]
    method = "est"
    common_name = "<name>"
    
    [provisioning.attestation.identity_cert.auto_renew]
    rotate_key = false
    threshold = "80%"
    retry = "4%"

    [cert_issuance.est]
        trusted_certs = [
            "file:///var/aziot/certs/digicert-root.cer", # note that this has also been installed on the system for good measure
        ]
       
    [cert_issuance.est.auth]
    username = "estuser"
    password = "<passcode>"
    
    [cert_issuance.est.urls]
    
    default = "https://clientauth.one.digicert.com/.well-known/est/IOT_<endpoint>"
    ```

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```


Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
‼ aziot-identity-service package is up-to-date - Warning
    Installed aziot-identity-service package has version 1.4.2 but 1.4.3 is the latest stable version available.
    Please see https://aka.ms/aziot-update-runtime for update instructions.
√ host time is close to reference time - OK
√ production readiness: identity certificates expiry - OK
√ production readiness: EST identity and bootstrap certificates expiry - OK
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ check all EST server URLs utilize HTTPS - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
‼ host can connect to and perform TLS handshake with iothub AMQP port - Warning
    Could not retrieve iothub_hostname from provisioning file.
    Please specify the backing IoT Hub name using --iothub-hostname switch if you have that information.
    Since no hostname is provided, all hub connectivity tests will be skipped.
‼ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - Warning
    Could not retrieve iothub_hostname from provisioning file.
    Please specify the backing IoT Hub name using --iothub-hostname switch if you have that information.
    Since no hostname is provided, all hub connectivity tests will be skipped.
‼ host can connect to and perform TLS handshake with iothub MQTT port - Warning
    Could not retrieve iothub_hostname from provisioning file.
    Please specify the backing IoT Hub name using --iothub-hostname switch if you have that information.
    Since no hostname is provided, all hub connectivity tests will be skipped.
√ host can connect to and perform TLS handshake with DPS endpoint - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
× configuration has correct URIs for daemon mgmt endpoint - Error
    SocketError - SocketErrorCode (TimedOut) : Operation timed out
    One or more errors occurred. (Got bad response: )
‼ aziot-edge package is up-to-date - Warning
    Installed IoT Edge daemon has version 1.4.8 but 1.4.9 is the latest stable version available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
√ production readiness: logs policy - OK
√ production readiness: Edge Agent's storage directory is persisted on the host filesystem - OK
√ production readiness: Edge Hub's storage directory is persisted on the host filesystem - OK
√ proxy settings are consistent in aziot-edged, aziot-identityd, moby daemon and config.toml - OK

Connectivity checks
-------------------
26 check(s) succeeded.
6 check(s) raised warnings. Re-run with --verbose for more details.
1 check(s) raised errors. Re-run with --verbose for more details.
7 check(s) were skipped due to errors from other checks. Re-run with --verbose for more details.

```
</details>

### Device Information
* Host OS: Ubuntu 20.04 
* Architecture: arm64
* Container OS: Linux containers/moby engine

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.4.8
* Edge Agent [image tag (e.g. 1.0.0)]: 1.4
* Edge Hub [image tag (e.g. 1.0.0)]:  1.4
* Docker/Moby [run `docker version`]: 
```
Client:
 Version:           20.10.22+azure-1
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b63ab20acfcc3f3550ea756a0561655a77
 Built:             Thu Dec 15 15:37:38 UTC 2022
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.22+azure-1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b314993e5eb3cc2776da0bbe41d5eb4b707b
  Built:            Thu Dec 15 22:17:04 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.5.16+azure-1
  GitCommit:        2e3140a0e09d288a9086474752b4478aa0964e7c
 nvidia:
  Version:          1.1.4
  GitCommit:        5fd4c4d144137e991c4acebb2146ab1483a97925
 docker-init:
  Version:          0.19.0
  GitCommit:        
```

## Logs
See above.

Note: I have tried increasing verbosity in the logs to both DEBUG and TRACE. There is no extra information that is useful.

## Additional Information
I have double checked the bootstrap certificates and permissions. They appear correct, but I won't rule out that as the issue.
