### ISSUE TITLE
aziot-keyd invalid parameter "id": not found

### ISSUE THREAD

**Issue by epomatti** [Azure/iotedge#7034]
## Expected Behavior
Configuration logs should have no errors, or if errors occur, should provide minimal information for troubleshooting.

## Current Behavior

Upon applying my configuration, I'm getting this error message in the logs (`sudo iotedge system logs`):

```
May 27 14:08:30 edgegateway.bluefactory.local aziot-keyd[1853]: 2023-05-27T14:08:30Z [ERR!] - invalid parameter "id": not found
```

My IoT Edge device has no issues, but I don't know what this error means and what implications it might have.

Here is a snippet from the logs:

```
May 27 14:08:30 edgegateway.bluefactory.local aziot-edged[1849]: 2023-05-27T14:08:30Z [INFO] - Watchdog checking Edge runtime status
May 27 14:08:30 edgegateway.bluefactory.local aziot-identityd[1851]: 2023-05-27T14:08:30Z [INFO] - <-- PUT /identities/modules/$edgeAgent?api-version=2020-09-01&type=aziot {"content-type": "application/json", "host": "identityd.sock", "content-length": "40"}
May 27 14:08:30 edgegateway.bluefactory.local aziot-keyd[1853]: 2023-05-27T14:08:30Z [INFO] - <-- POST /encrypt?api-version=2021-05-01 {"content-length": "355", "content-type": "application/json"}
May 27 14:08:30 edgegateway.bluefactory.local aziot-keyd[1853]: 2023-05-27T14:08:30Z [INFO] - --> 200 {"content-type": "application/json"}
May 27 14:08:30 edgegateway.bluefactory.local aziot-keyd[1853]: 2023-05-27T14:08:30Z [INFO] - <-- GET /key/aziot_identityd_master_id?api-version=2021-05-01 {"host": "keyd.sock"}
May 27 14:08:30 edgegateway.bluefactory.local aziot-keyd[1853]: 2023-05-27T14:08:30Z [ERR!] - invalid parameter "id": not found
May 27 14:08:30 edgegateway.bluefactory.local aziot-keyd[1853]: 2023-05-27T14:08:30Z [INFO] - !!! a parameter has an invalid value
May 27 14:08:30 edgegateway.bluefactory.local aziot-keyd[1853]: 2023-05-27T14:08:30Z [INFO] - --> 400 {"content-type": "application/json"}
May 27 14:08:30 edgegateway.bluefactory.local aziot-keyd[1853]: 2023-05-27T14:08:30Z [INFO] - <-- POST /key?api-version=2021-05-01 {"content-type": "application/json", "host": "keyd.sock", "content-length": "75"}
```

## Steps to Reproduce

Apply the following `/etc/aziot/config.toml` file (`sudo iotedge config apply`):

```toml
# ==============================================================================
# Hostname
# ==============================================================================

hostname = "edgegateway.bluefactory.local"


# ==============================================================================
# Trust bundle cert
# ==============================================================================

trust_bundle_cert = "file:///var/secrets/aziot/azure-iot-test-only.root.ca.cert.pem"


# Provisioning configuration
# --------------------------

# Manual provisioning with X.509 certificate
[provisioning]
source = "manual"
iothub_hostname = "iot-<redacted>.azure-devices.net"
device_id = "EdgeGateway"

[provisioning.authentication]
method = "x509"

# identity certificate private key
identity_pk = "file:///var/secrets/aziot/iot-edge-device-identity-edgegateway.<redacted>.key.pem"

# identity certificate
identity_cert = "file:///var/secrets/aziot/iot-edge-device-identity-edgegateway.<redacted>-full-chain.cert.pem"

# ==============================================================================
# Edge CA certificate
# ==============================================================================

# Edge CA certificate loaded from a file:
# ---------------------

[edge_ca]
cert = "file:///var/secrets/aziot/iot-edge-device-ca-edgeca.<redacted>-full-chain.cert.pem"
pk = "file:///var/secrets/aziot/iot-edge-device-ca-edgeca<redacted>.key.pem"
```

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
√ aziot-identity-service package is up-to-date - OK
√ host time is close to reference time - OK
√ production readiness: identity certificates expiry - OK
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ check all EST server URLs utilize HTTPS - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
√ host can connect to and perform TLS handshake with iothub AMQP port - OK
√ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with iothub MQTT port - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
√ configuration has correct URIs for daemon mgmt endpoint - OK
√ aziot-edge package is up-to-date - OK
√ container time is close to host time - OK
√ DNS server - OK
√ production readiness: logs policy - OK
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
        caused by: The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
                   Data might be lost if the module is deleted or updated.
                   Please see https://aka.ms/iotedge-storage-host for best practices.
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container
        caused by: Could not check current state of edgeHub container
        caused by: docker returned exit status: 1, stderr = Error: No such object: edgeHub
√ Agent image is valid and can be pulled from upstream - OK
√ proxy settings are consistent in aziot-edged, aziot-identityd, moby daemon and config.toml - OK

Connectivity checks
-------------------
√ container on the default network can connect to upstream AMQP port - OK
√ container on the default network can connect to upstream HTTPS / WebSockets port - OK
√ container on the default network can connect to upstream MQTT port - OK
    skipping because of not required in this configuration
√ container on the IoT Edge module network can connect to upstream AMQP port - OK
√ container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to upstream MQTT port - OK
    skipping because of not required in this configuration
34 check(s) succeeded.
1 check(s) raised warnings.
1 check(s) raised errors.
2 check(s) were skipped due to errors from other checks.

```
</details>

### Device Information
* Host OS:  20.04.6 LTS
* Architecture: linux/amd64
* Container OS: Linux container 

### Runtime Versions
* aziot-edged: iotedge 1.4.10
* Edge Agent: 1.4
* Edge Hub: Not deployed yet (fresh install)
* Docker/Moby: 20.10.25+azure-1

## Logs

<details>
<summary>aziot-edged logs</summary>

```

May 27 14:08:30 edgegateway.<redacted> aziot-edged[1849]: 2023-05-27T14:08:30Z [INFO] - Watchdog checking Edge runtime status
May 27 14:08:30 edgegateway.<redacted> aziot-identityd[1851]: 2023-05-27T14:08:30Z [INFO] - <-- PUT /identities/modules/$edgeAgent?api-version=2020-09-01&type=aziot {"content-type": "application/json", "host": "identityd.sock", "content-length": "40"}
May 27 14:08:30 edgegateway<redacted> aziot-keyd[1853]: 2023-05-27T14:08:30Z [INFO] - <-- POST /encrypt?api-version=2021-05-01 {"content-length": "355", "content-type": "application/json"}
May 27 14:08:30 edgegateway.<redacted> aziot-keyd[1853]: 2023-05-27T14:08:30Z [INFO] - --> 200 {"content-type": "application/json"}
May 27 14:08:30 edgegateway.<redacted> aziot-keyd[1853]: 2023-05-27T14:08:30Z [INFO] - <-- GET /key/aziot_identityd_master_id?api-version=2021-05-01 {"host": "keyd.sock"}
May 27 14:08:30 edgegateway.<redacted> aziot-keyd[1853]: 2023-05-27T14:08:30Z [ERR!] - invalid parameter "id": not found
May 27 14:08:30 edgegateway.<redacted> aziot-keyd[1853]: 2023-05-27T14:08:30Z [INFO] - !!! a parameter has an invalid value
May 27 14:08:30 edgegateway<redacted> aziot-keyd[1853]: 2023-05-27T14:08:30Z [INFO] - --> 400 {"content-type": "application/json"}
May 27 14:08:30 edgegateway<redacted> aziot-keyd[1853]: 2023-05-27T14:08:30Z [INFO] - <-- POST /key?api-version=2021-05-01 {"content-type": "application/json", "host": "keyd.sock", "content-length": "75"}

```
</details>

<details>
<summary>edge-agent logs</summary>

```

2023-05-27 14:08:40  Starting Edge Agent
2023-05-27 14:08:40  Creating UID 13622 as edgeagentuser
2023-05-27 14:08:40  Creating storage folder: /tmp/edgeAgent
2023-05-27 14:08:40  Creating backup folder: /tmp/edgeAgent_backup
2023-05-27 14:08:40  Changing ownership of management socket: /var/run/iotedge/mgmt.sock
2023-05-27 14:08:40  Completed necessary setup. Starting Edge Agent.
2023-05-27 14:08:40.400 +00:00 Edge Agent Main()
<6> 2023-05-27 14:08:40.541 +00:00 [INF] - Initializing Edge Agent.
<6> 2023-05-27 14:08:40.665 +00:00 [INF] - Version - 1.4.11.73886408 (3a2e68e378301fd132d7057dbdb0de7bcb9b181b)
<6> 2023-05-27 14:08:40.666 +00:00 [INF] -
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

<6> 2023-05-27 14:08:40.668 +00:00 [INF] - ModuleUpdateMode: NonBlocking
<6> 2023-05-27 14:08:40.721 +00:00 [INF] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false}
<6> 2023-05-27 14:08:40.822 +00:00 [INF] - Installing certificates [CN=edgeca.bluefactory.local.ca:06/26/2023 13:32:27],[CN=Azure_IoT_Hub_Intermediate_Cert_Test_Only:06/26/2023 13:32:26],[CN=Azure_IoT_Hub_CA_Cert_Test_Only:06/26/2023 13:32:25],[CN=Azure_IoT_Hub_CA_Cert_Test_Only:06/26/2023 13:32:25] to Root
<6> 2023-05-27 14:08:40.984 +00:00 [INF] - Starting metrics listener on Host: *, Port: 9600, Suffix: metrics
<6> 2023-05-27 14:08:41.003 +00:00 [INF] - Updating performance metrics every 05m:00s
<6> 2023-05-27 14:08:41.009 +00:00 [INF] - Started operation Get system resources
<6> 2023-05-27 14:08:41.010 +00:00 [INF] - Collecting metadata metrics
<6> 2023-05-27 14:08:41.094 +00:00 [INF] - Set metadata metrics: 1.4.11.73886408 (3a2e68e378301fd132d7057dbdb0de7bcb9b181b), {"Enabled":false,"DisableCloudSubscriptions":false}, {"OperatingSystemType":"Linux","Architecture":"x86_64","Version":"1.4.10","Provisioning":{"Type":"ProvisioningType","DynamicReprovisioning":false,"AlwaysReprovisionOnStartup":false},"ServerVersion":"20.10.25+azure-1","KernelVersion":"#45~20.04.1-Ubuntu SMP Tue Apr 25 18:45:15 UTC 2023","OperatingSystem":"ubuntu","NumCpus":1,"TotalMemory":2005417984,"Virtualized":"yes"}, True
<6> 2023-05-27 14:08:41.111 +00:00 [INF] - Started operation Checkpoint Availability
<6> 2023-05-27 14:08:41.113 +00:00 [INF] - Started operation refresh twin config
<6> 2023-05-27 14:08:41.134 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...
<6> 2023-05-27 14:08:41.431 +00:00 [INF] - Created persistent store at /tmp/edgeAgent
<6> 2023-05-27 14:08:41.496 +00:00 [INF] - Started operation Metrics Scrape
<6> 2023-05-27 14:08:41.496 +00:00 [INF] - Started operation Metrics Upload
Scraping frequency: 01:00:00
Upload Frequency: 1.00:00:00
<6> 2023-05-27 14:08:42.277 +00:00 [INF] - Registering request handler UploadModuleLogs
<6> 2023-05-27 14:08:42.277 +00:00 [INF] - Registering request handler GetModuleLogs
<6> 2023-05-27 14:08:42.277 +00:00 [INF] - Registering request handler UploadSupportBundle
<6> 2023-05-27 14:08:42.277 +00:00 [INF] - Registering request handler RestartModule
<6> 2023-05-27 14:08:42.577 +00:00 [INF] - Edge agent connected to IoT Hub via Amqp_Tcp_Only.
<6> 2023-05-27 14:08:42.650 +00:00 [INF] - Initialized new module client with subscriptions enabled
<6> 2023-05-27 14:08:42.705 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 1 and reported properties version 1.
<6> 2023-05-27 14:08:42.709 +00:00 [INF] - Deployment config in edge agent's desired properties is empty.
<3> 2023-05-27 14:08:42.711 +00:00 [ERR] - Error refreshing edge agent configuration from twin.
Microsoft.Azure.Devices.Edge.Agent.Core.ConfigSources.ConfigEmptyException: This device has an empty configuration for the edge agent. Please set a deployment manifest.
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.UpdateDeploymentConfig(TwinCollection desiredProperties) in /mnt/vss/_work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 436
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.<RefreshTwinAsync>b__40_0(Twin twin) in /mnt/vss/_work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 343
<6> 2023-05-27 14:08:42.921 +00:00 [INF] - Updated reported properties

```
</details>

<details>
<summary>edge-hub logs</summary>

```

Not installed yet, fresh install.

```
</details>
