### ISSUE TITLE
Question EST server configuration

### ISSUE THREAD

**Issue by YohskDista** [Azure/iotedge#7063]
OS Version: Windows 10 Enterprise 22H2
IoT Edge version: 1.4.10
Using EflowVM for IoT Edge Linux on Windows

Hello everyone,

After a few months that we are trying Azure IoT Hub using IoT Edge devices, we wanted to put in production mode the device and, to do so, we followed Microsoft documentation [here](https://learn.microsoft.com/en-us/azure/iot-edge/production-checklist?view=iotedge-1.4).
In this documentation, one of the first point is to install the production certificate and we followed the step to configure our IoT Edge with an EST server. So we asked GlobalSign to have a demo account to test with that.

We started to follow this [explanation](https://techcommunity.microsoft.com/t5/internet-of-things-blog/automatic-iot-edge-certificate-management-with-globalsign-est/ba-p/3739767) given by GlobalSign to help us configure the IoT Edge. But it's been a week now that we are struggling with the configuration of the IoT Edge, probably because missunderstanding of the documentation.

We received 3 endpoints from GlobalSign which are:

https://demo-1.est.edge.globalsign.com:443/.well-known/est/ [iDevID] 
 
https://demo-2.est.edge.globalsign.com:443/.well-known/est/ [Edge CA] 
 
https://demo-3.est.edge.globalsign.com:443/.well-known/est/  [LDevID]

Following the explanation of GlobalSign we configured the `config.toml` file like this:

```toml
# The CA cert of the demo root we got from earlier
[cert_issuance.est]
trusted_certs = [
  "file:///var/aziot/certs/root.cert.pem",
]

# Empty because the LDevID (device ID) and Edge CA endpoints are different
[cert_issuance.est.urls]

# Use the IDevID cert and private key for authentication to EST
[cert_issuance.est.auth]
identity_cert = "file:///var/aziot/certs/idevid.cert.pem"
identity_pk = "file:///var/aziot/secrets/idevid.key.pem"

# DPS provisioning with X.509 certificate
# Replace with ID Scope from your DPS
[provisioning]
source = "dps"
global_endpoint = "https://global.azure-devices-provisioning.net"
id_scope = "<DPS Scope ID>"

[provisioning.attestation]
method = "x509"
registration_id = "my-device-id"

# Get LDevID (device ID) cert from EST with auto renew
[provisioning.attestation.identity_cert]
method = "est"
common_name = "my-device-id"
url = "https://demo-3.est.edge.globalsign.com:443/.well-known/est/"

[provisioning.attestation.identity_cert.auto_renew]
rotate_key = true
threshold = "80%"
retry = "4%"

# Get Edge CA from EST also with auto renew
[edge_ca]
method = "est"
url = "https://demo-2.est.edge.globalsign.com:443/.well-known/est/"

[edge_ca.auto_renew]
rotate_key = true
threshold = "80%" 
retry = "4%"
```

Whe we run the `sudo iotedge check` command we get this information:

<details>
<summary>IoT Edge check</summary>

```
Configuration checks (aziot-identity-service)

√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
√ aziot-identity-service package is up-to-date - OK
√ host time is close to reference time - OK
√ production readiness: identity certificates expiry - OK
√ production readiness: EST identity and bootstrap certificates expiry - OK
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
× read all preloaded certificates from the Certificates Service - Error
    could not load cert with ID "aziot-edged-trust-bundle"
    
    Caused by:
        0: connection error: Connection reset by peer (os error 104)
        1: Connection reset by peer (os error 104)
    could not load cert with ID "est-id"
    
    Caused by:
        0: error trying to connect: Connection refused (os error 111)
        1: Connection refused (os error 111)
    could not load cert with ID "est-server-ca-1"
    
    Caused by:
        0: error trying to connect: Connection refused (os error 111)
        1: Connection refused (os error 111)
√ read all preloaded key pairs from the Keys Service - OK
√ check all EST server URLs utilize HTTPS - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
‼ host can connect to and perform TLS handshake with iothub AMQP port - Warning
    Could not retrieve iothub_hostname from provisioning file.
    Please specify the backing IoT Hub name using --iothub-hostname switch if you have that information.
    Since no hostname is provided, all hub connectivity tests will be skipped.
‼ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - Warning
    Could not retrieve iothub_hostname from provisioning file.
    Please specify the backing IoT Hub name using --iothub-hostname switch if you have that information.
    Since no hostname is provided, all hub connectivity tests will be skipped.
‼ host can connect to and perform TLS handshake with iothub MQTT port - Warning
    Could not retrieve iothub_hostname from provisioning file.
    Please specify the backing IoT Hub name using --iothub-hostname switch if you have that information.
    Since no hostname is provided, all hub connectivity tests will be skipped.
√ host can connect to and perform TLS handshake with DPS endpoint - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
× configuration has correct URIs for daemon mgmt endpoint - Error
    SocketError - SocketErrorCode (TimedOut) : Operation timed out
    One or more errors occurred. (Got bad response: )
√ aziot-edge package is up-to-date - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
× production readiness: Edge Agent's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeAgent container
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container
√ proxy settings are consistent in aziot-edged, aziot-identityd, moby daemon and config.toml - OK

Connectivity checks
-------------------
24 check(s) succeeded.
5 check(s) raised warnings. Re-run with --verbose for more details.
4 check(s) raised errors. Re-run with --verbose for more details.
7 check(s) were skipped due to errors from other checks. Re-run with --verbose for more details.

```
</details>

The issue seems to be when it tries to load the preloaded certificate and, as you can see below, the `aziot-certd` service is in error due to that.

<details>
<summary>System status</summary>

```
System services:
    aziot-edged             Running
    aziot-identityd         Running
    aziot-keyd              Running
    aziot-certd             Down - activating 
    aziot-tpmd              Ready

aziot-certd is in a bad state because:
aziot-certd.service: Down - activating : Printing the last 10 log lines.
Jul 20 05:23:47 GASTRIX-EFLOW systemd[1]: Started Azure IoT Certificates Service.
Jul 20 05:23:47 GASTRIX-EFLOW aziot-certd[3876]: 2023-07-20T05:23:47Z [INFO] - Starting service...
Jul 20 05:23:47 GASTRIX-EFLOW aziot-certd[3876]: 2023-07-20T05:23:47Z [INFO] - Version - dev build
Jul 20 05:23:47 GASTRIX-EFLOW aziot-certd[3876]: 2023-07-20T05:23:47Z [ERR!] - service encountered an error
Jul 20 05:23:47 GASTRIX-EFLOW aziot-certd[3876]: 2023-07-20T05:23:47Z [ERR!] - caused by: parameter "cert_id" has an invalid value
Jul 20 05:23:47 GASTRIX-EFLOW aziot-certd[3876]: 2023-07-20T05:23:47Z [ERR!] - caused by: cert "est-id" is configured to be issued by EST, but EST URL is not configured
Jul 20 05:23:47 GASTRIX-EFLOW aziot-certd[3876]: 2023-07-20T05:23:47Z [ERR!] -    0: backtrace::capture::Backtrace::create
Jul 20 05:23:47 GASTRIX-EFLOW aziot-certd[3876]:    1: backtrace::capture::Backtrace::new
Jul 20 05:23:47 GASTRIX-EFLOW systemd[1]: aziot-certd.service: Main process exited, code=exited, status=1/FAILURE
Jul 20 05:23:47 GASTRIX-EFLOW systemd[1]: aziot-certd.service: Failed with result 'exit-code'.

Use 'iotedge system logs' to check for non-fatal errors.
Use 'iotedge check' to diagnose connectivity and configuration issues.

```
</details>

Did someone already experienced that or see something completely wrong in the configuration?

Thank you for your help!

**Comment by ggjjj** [comment]
This could be possible if certs are not valid. Can you recheck?

**Comment by YohskDista** [comment]
I checked the root cert (expires in march 2025) and the device-id cert (expires 29th of July 2023). I tried to use the authentication with the username/password. The connection seems to work (even if it's not something great for production deployment) but I have another problem:

<details>
<summary>System status</summary>

```
System services:
    aziot-edged             Running
    aziot-identityd         Down - activating 
    aziot-keyd              Running
    aziot-certd             Running
    aziot-tpmd              Ready

aziot-identityd is in a bad state because:
aziot-identityd.service: Down - activating : Printing the last 10 log lines.
Jul 24 06:25:52 TEST-EFLOW aziot-identityd[2990]: 2023-07-24T06:25:52Z [INFO] - Starting service...
Jul 24 06:25:52 TEST-EFLOW aziot-identityd[2990]: 2023-07-24T06:25:52Z [INFO] - Version - dev build
Jul 24 06:25:52 TEST-EFLOW aziot-identityd[2990]: 2023-07-24T06:25:52Z [ERR!] - service encountered an error
Jul 24 06:25:52 TEST-EFLOW aziot-identityd[2990]: 2023-07-24T06:25:52Z [ERR!] - caused by: internal error
Jul 24 06:25:52 TEST-EFLOW aziot-identityd[2990]: 2023-07-24T06:25:52Z [ERR!] - caused by: could not create certificate
Jul 24 06:25:52 TEST-EFLOW aziot-identityd[2990]: 2023-07-24T06:25:52Z [ERR!] - caused by: failed to generate new key: internal error
Jul 24 06:25:52 TEST-EFLOW aziot-identityd[2990]: 2023-07-24T06:25:52Z [ERR!] -    0: backtrace::capture::Backtrace::create
Jul 24 06:25:52 TEST-EFLOW aziot-identityd[2990]:    1: backtrace::capture::Backtrace::new
Jul 24 06:25:52 TEST-EFLOW systemd[1]: aziot-identityd.service: Main process exited, code=exited, status=1/FAILURE
Jul 24 06:25:52 TEST-EFLOW systemd[1]: aziot-identityd.service: Failed with result 'exit-code'.

Use 'iotedge system logs' to check for non-fatal errors.
Use 'iotedge check' to diagnose connectivity and configuration issues.
```
</details>

**Comment by ggjjj** [comment]
Are you still using EST? what do you mean by authentication with username and password? The error is because of the failure in creating identity certs and so the service is down. @YohskDista

**Comment by YohskDista** [comment]
Yes I am still using EST (as far as I know and I understand the documentation). I changed:

```toml
[cert_issuance.est.auth]
identity_cert = "file:///var/aziot/certs/idevid.cert.pem"
identity_pk = "file:///var/aziot/secrets/idevid.key.pem"
```

as following:

```toml
[cert_issuance.est.auth]
username = "user"
password = "XXXXXXXXXXX"
```

and the log changed as I sent you yesterday. I can go back to a certificate authentication but then I go back to the previous problem and the logs that are in my first message

**Comment by ggjjj** [comment]
what is the error message in the new log?

**Comment by jlian** [comment]
Hmm, this is weird. It's complaining that the EST ID cert is configured to be issued from the EST server and the URL is missing. But your config actually doesn't do that, the `[cert_issuance.est.urls]` config is optional: 

https://github.com/Azure/iotedge/blob/main/edgelet/doc/est.md#sample-configuration 

@ggjjj do you know if there were any changes on our side for EST ID cert issuance config?

@YohskDista I didn't think GlobalSign supported username/password auth, maybe that's why you're getting the key error

Instead, can you try to redo your config more like [this example](https://github.com/Azure/iotedge/blob/main/edgelet/doc/est.md#sample-configuration ), like put `file:///var/aziot/certs/idevid.cert.pem` as `bootstrap_identity_cert` under the identity and Edge CA configs

**Comment by jlian** [comment]
Another thing to try is to set your IDevID URL like this

```toml
[cert_issuance.est.urls]
default = "https://demo-1.est.edge.globalsign.com:443/.well-known/est/"
```
